language: c++

os:
  - linux
  - osx
env:
  matrix:
      - RPCLIB_CXX_STANDARD=14 BUILD_TYPE=Debug
      - RPCLIB_CXX_STANDARD=11 BUILD_TYPE=Debug
      - RPCLIB_CXX_STANDARD=14 BUILD_TYPE=Release
      - RPCLIB_CXX_STANDARD=11 BUILD_TYPE=Release

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsfml-dev

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sfml ; fi
  - pip install --user cpp-coveralls

script:
  - mkdir build ; cd build
  - cmake -DRPCLIB_ENABLE_COVERAGE=ON -DRPCLIB_BUILD_TESTS=ON -DRPCLIB_CXX_STANDARD=$RPCLIB_CXX_STANDARD -DCMAKE_INSTALL_PREFIX=../install ..
  - cmake --build . --config $BUILD_TYPE
  - cmake --build . --target install

after_success:
  - ../install/bin/rpc_test
  - coveralls --exclude dependencies --exclude test --exclude include/rpc/msgpack --exclude include/rcp/msgpack.hpp --gcov /usr/bin/gcov-5
